"""Create world tables

Revision ID: 0001_create_world_tables
Revises:
Create Date: 2025-10-25 04:00:00.000000

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import json
import os

# revision identifiers, used by Alembic.
revision: str = '0001_create_world_tables'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """This function runs when you 'upgrade head'"""
    # ### Create Factions Table ###
    factions_table = op.create_table('factions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('disposition', sa.JSON(), nullable=True),
    sa.Column('resources', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_factions_id'), 'factions', ['id'], unique=False)
    op.create_index(op.f('ix_factions_name'), 'factions', ['name'], unique=True)

    # ### Create Regions Table ###
    regions_table = op.create_table('regions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('current_weather', sa.String(), nullable=True),
    sa.Column('environmental_effects', sa.JSON(), nullable=True),
    sa.Column('faction_influence', sa.JSON(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_regions_id'), 'regions', ['id'], unique=False)
    op.create_index(op.f('ix_regions_name'), 'regions', ['name'], unique=True)

    # ### Create Locations Table ###
    locations_table = op.create_table('locations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('tags', sa.JSON(), nullable=True),
    sa.Column('exits', sa.JSON(), nullable=True),
    sa.Column('generated_map_data', sa.JSON(), nullable=True),
    sa.Column('map_seed', sa.String(), nullable=True),
    sa.Column('region_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['region_id'], ['regions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_locations_id'), 'locations', ['id'], unique=False)
    op.create_index(op.f('ix_locations_name'), 'locations', ['name'], unique=False)

    # ### Create NPC Instances Table ###
    op.create_table('npc_instances',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('template_id', sa.String(), nullable=True),
    sa.Column('name_override', sa.String(), nullable=True),
    sa.Column('current_hp', sa.Integer(), nullable=True),
    sa.Column('max_hp', sa.Integer(), nullable=True),
    sa.Column('status_effects', sa.JSON(), nullable=True),
    sa.Column('location_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['location_id'], ['locations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_npc_instances_id'), 'npc_instances', ['id'], unique=False)
    op.create_index(op.f('ix_npc_instances_template_id'), 'npc_instances', ['template_id'], unique=False)

    # ### Create Item Instances Table ###
    op.create_table('item_instances',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('template_id', sa.String(), nullable=True),
    sa.Column('quantity', sa.Integer(), nullable=True),
    sa.Column('location_id', sa.Integer(), nullable=True),
    sa.Column('npc_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['location_id'], ['locations.id'], ),
    sa.ForeignKeyConstraint(['npc_id'], ['npc_instances.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_item_instances_id'), 'item_instances', ['id'], unique=False)
    op.create_index(op.f('ix_item_instances_template_id'), 'item_instances', ['template_id'], unique=False)

    # ### Seed Data ###
    data_dir = os.path.join(os.path.dirname(__file__), '..', '..', 'data')

    with open(os.path.join(data_dir, "initial_factions.json"), "r") as f:
        factions_data = json.load(f)
        op.bulk_insert(factions_table, factions_data)

    with open(os.path.join(data_dir, "initial_regions.json"), "r") as f:
        regions_data = json.load(f)
        op.bulk_insert(regions_table, regions_data)

    with open(os.path.join(data_dir, "initial_locations.json"), "r") as f:
        locations_data = json.load(f)
        op.bulk_insert(locations_table, locations_data)


def downgrade() -> None:
    """This function runs if you need to undo the migration"""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_item_instances_template_id'), table_name='item_instances')
    op.drop_index(op.f('ix_item_instances_id'), table_name='item_instances')
    op.drop_table('item_instances')
    op.drop_index(op.f('ix_npc_instances_template_id'), table_name='npc_instances')
    op.drop_index(op.f('ix_npc_instances_id'), table_name='npc_instances')
    op.drop_table('npc_instances')
    op.drop_index(op.f('ix_locations_name'), table_name='locations')
    op.drop_index(op.f('ix_locations_id'), table_name='locations')
    op.drop_table('locations')
    op.drop_index(op.f('ix_regions_name'), table_name='regions')
    op.drop_index(op.f('ix_regions_id'), table_name='regions')
    op.drop_table('regions')
    op.drop_index(op.f('ix_factions_name'), table_name='factions')
    op.drop_index(op.f('ix_factions_id'), table_name='factions')
    op.drop_table('factions')
    # ### end Alembic commands ###
