"""Add traps, annotations, behavior

Revision ID: 2edc8d502cb2
Revises: 0001_create_world_tables
Create Date: 2025-10-26 18:51:32.757922

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2edc8d502cb2'
down_revision = '0001_create_world_tables'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('trap_instances',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('template_id', sa.String(), nullable=True),
    sa.Column('location_id', sa.Integer(), nullable=True),
    sa.Column('coordinates', sa.JSON(), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['location_id'], ['locations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_trap_instances_id'), 'trap_instances', ['id'], unique=False)
    op.create_index(op.f('ix_trap_instances_status'), 'trap_instances', ['status'], unique=False)
    op.create_index(op.f('ix_trap_instances_template_id'), 'trap_instances', ['template_id'], unique=False)
    op.add_column('locations', sa.Column('ai_annotations', sa.JSON(), nullable=True))
    op.add_column('npc_instances', sa.Column('behavior_tags', sa.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('npc_instances', 'behavior_tags')
    op.drop_column('locations', 'ai_annotations')
    op.drop_index(op.f('ix_trap_instances_template_id'), table_name='trap_instances')
    op.drop_index(op.f('ix_trap_instances_status'), table_name='trap_instances')
    op.drop_index(op.f('ix_trap_instances_id'), table_name='trap_instances')
    op.drop_table('trap_instances')
    # ### end Alembic commands ###
