"""add coordinates to npc and item instances

Revision ID: a4d6d63e365c
Revises: 2edc8d502cb2
Create Date: 2025-10-30 22:46:53.828791

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a4d6d63e365c'
down_revision = '2edc8d502cb2'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('item_instances', sa.Column('coordinates', sa.JSON(), nullable=True))
    op.add_column('npc_instances', sa.Column('coordinates', sa.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('npc_instances', 'coordinates')
    op.drop_column('item_instances', 'coordinates')
    # ### end Alembic commands ###
