"""add_current_location_id

Revision ID: 1dd3ea93d569
Revises: 8bbdfcb6ca00
Create Date: 2025-11-05 04:54:05.565097

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1dd3ea93d569'
down_revision: Union[str, Sequence[str], None] = '8bbdfcb6ca00'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
