"""Add current_location_id to Character model

Revision ID: 8bbdfcb6ca00
Revises: c35e834722b0
Create Date: 2025-11-05 01:52:08.883698

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8bbdfcb6ca00'
down_revision: Union[str, Sequence[str], None] = 'c35e834722b0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('characters', sa.Column('current_location_id', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('characters', 'current_location_id')
    # ### end Alembic commands ###
