"""Create story tables

Revision ID: 0001_create_story_tables
Revises:
Create Date: 2025-10-25 04:30:00.000000

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0001_create_story_tables'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### Create Campaigns Table ###
    op.create_table('campaigns',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('main_plot_summary', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_campaigns_id'), 'campaigns', ['id'], unique=False)

    # ### Create ActiveQuests Table ###
    op.create_table('active_quests',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('steps', sa.JSON(), nullable=True),
    sa.Column('current_step', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('campaign_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['campaign_id'], ['campaigns.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_active_quests_id'), 'active_quests', ['id'], unique=False)
    op.create_index(op.f('ix_active_quests_status'), 'active_quests', ['status'], unique=False)
    op.create_index(op.f('ix_active_quests_title'), 'active_quests', ['title'], unique=False)

    # ### Create StoryFlags Table ###
    op.create_table('story_flags',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('flag_name', sa.String(), nullable=True),
    sa.Column('value', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_story_flags_flag_name'), 'story_flags', ['flag_name'], unique=True)
    op.create_index(op.f('ix_story_flags_id'), 'story_flags', ['id'], unique=False)


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_story_flags_id'), table_name='story_flags')
    op.drop_index(op.f('ix_story_flags_flag_name'), table_name='story_flags')
    op.drop_table('story_flags')
    op.drop_index(op.f('ix_active_quests_title'), table_name='active_quests')
    op.drop_index(op.f('ix_active_quests_status'), table_name='active_quests')
    op.drop_index(op.f('ix_active_quests_id'), table_name='active_quests')
    op.drop_table('active_quests')
    op.drop_index(op.f('ix_campaigns_id'), table_name='campaigns')
    op.drop_table('campaigns')
    # ### end Alembic commands ###